 DROP TABLE FICHA;
CREATE TABLE FICHA (
	NUMFICHA INTEGER NOT NULL AUTO_INCREMENT,
	MATRICULA NUMERIC(12,0),
	NOMESERVIDOR VARCHAR(60),
	NOMEMAE VARCHAR(60),
	DTNASC DATE,
	CPF VARCHAR(14),
	CODLOCAL INTEGER,
	ESTANTE INTEGER,
	PRATELEIRA INTEGER,
	SITFICHA CHAR(3),
	CODUSUEMP INTEGER,
	RG NUMERIC(15,0),
	ORGAOEXP CHAR(3),
	UF CHAR(2),
	PRIMARY KEY (NUMFICHA)
);

SELECT * FROM FICHA