 DROP TABLE FICHA;
CREATE TABLE FICHA (
	NUMFICHA INTEGER NOT NULL AUTO_INCREMENT,
	MATRICULA NUMERIC(12,0),
	NOMESERVIDOR VARCHAR(60),
	NOMEMAE VARCHAR(60),
	DTNASC DATE,
	CPF VARCHAR(14),
	CODLOCAL INTEGER,
	ESTANTE INTEGER,
	PRATELEIRA INTEGER,
	SITFICHA CHAR(3),
	CODUSUEMP INTEGER,
	RG NUMERIC(15,0),
	ORGAOEXP CHAR(3),
	UF CHAR(2),
	PRIMARY KEY (NUMFICHA)
);

-- Ajusta a data de nascimento para 0000 onde data for vazio. 
UPDATE FICHA_2 SET DTNASC= "0000-00-00" WHERE DTNASC="" ;

-- ALTERANDO O TIPO DE DADO DA DA COLUNA NASCIMENTO APOS OS DADOS SEREM IMPORTADOS
ALTER TABLE ficha_202007141819 MODIFY DTNASC DATE;

-- Ajustar o CPF PARA TIRAR OS PONTOS
SET SQL_SAFE_UPDATES=0;
UPDATE FICHA_2 SET CPF = REPLACE( REPLACE( CPF, '.', '' ), '-', '' );

-- AJUSTA O CODLOCAL PARA ZERO ONDE FOR VAZIO.
UPDATE FICHA_2 SET CODLOCAL= "0" WHERE CODLOCAL="" ;
