-- MOVPROC definition

-- Drop table

-- DROP TABLE MOVPROC;

CREATE TABLE MOVPROC (
	SEQMOV INTEGER NOT NULL AUTO_INCREMENT,
	CODUSUARIO INTEGER,
	NOMEUSUARIO VARCHAR(60),
	MATRICULAUSU INTEGER,
	DEPUSU INTEGER,
	DTRETPROC DATE,
	DTPREVPROC DATE,
	DTENTRPROC DATE,
	NUMFICHA INTEGER,
	SITPROC CHAR(1),
    PRIMARY KEY (SEQMOV)
);